### ISSUE TITLE
Measuring request times 10e-9

### ISSUE THREAD

**Issue by andrewmorrison1** [KxSystems/prometheus-kdb-exporter#12]
If we want to measure the number of seconds a request takes I think it should be 

tm:(1e-9)*.z.p-tmp

on line 114 of q/exporter.q

compared with what we have its 10e-9, but this is tens of seconds, i.e. 0D00:00:01.000000*10e-9 equals 10f not 1f.

**Comment by cmccarthy1** [comment]
This is closed by #13
